twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      joystick:
        topic: joy_vel
        timeout: 0.5
        priority: 99
      navigation:
        topic: /nav_vel
        timeout: 0.5
        priority: 50
